### ISSUE TITLE
Create @threefold/common package

### ISSUE THREAD

**Issue by MohamedElmdary** [threefoldtech/tfgrid-sdk-ts#989]
`@threefold/common` package should include the common parts from ui app for example playground and dashboard

## Related Issues
- https://github.com/threefoldtech/tfgrid-sdk-ts/issues/468

### TODO
- [x] Initialize vue3 project
- [x] Move validation components (form + input)
- [x] Move utils components (passwordInputWrapper, ...etc)
- [x] Move grid utils (getGrid, loadBalance, ...etc)
- [x] Move tfchain wallet connector
